### ISSUE TITLE
why not put add you result in your code

### ISSUE THREAD

**Issue by miderxi** [muhaochen/seq_ppi#10]

**Comment by muhaochen** [comment]
![image](https://user-images.githubusercontent.com/12452252/115583672-b7a50380-a28f-11eb-973f-72747e5ad7eb.png)

There is a link to the paper in the readme and the results are just one click away:
DOI: http://dx.doi.org/10.1093/bioinformatics/btz328

**Comment by miderxi** [comment]
ok
