### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bmd2007** [muhaochen/seq_ppi#12]
Hello,

I'm working on trying to implement several PPI prediction algorithms into a unified framework, however many of the github repositories I've come across from papers do not have any license associated with them.  Could you please add a license to your code so I know how its able to be used (preferably MIT, BSD3.0, or some other open source permissive license or a statement stating it can be used for any reason to allow the code to be used without any restrictions).

Thanks.

**Comment by muhaochen** [comment]
Thanks @bmd2007 for the suggestion. I have added an Apache 2.0 license to the repository.

-Muhao
