### ISSUE TITLE
Basic run: embeddings missing

### ISSUE THREAD

**Issue by ddofer** [muhaochen/seq_ppi#13]
I tried to run the default cnn.py model/script, with the "old" package version,  and get the following error (a file seems to be missing):

`C:\Users\Dan Ofer\Desktop\Stuff\Datasets\seq_ppi-master\binary\model\cnn\cnn.py in <module>()
     79     n_epochs = int(n_epochs)
     80
---> 81 seq2t = s2t(emb_files[use_emb])
     82
     83 max_data = -1

C:\Users\Dan Ofer\Desktop\Stuff\Datasets\seq_ppi-master\embeddings\seq2tensor.py in __init__(self, filename)
      6         self.t2v = {}
      7         self.dim = None
----> 8         for line in open(filename):
      9             line = line.strip().split('\t')
     10             t = line[0]

FileNotFoundError: [Errno 2] No such file or directory: '../../../embeddings/default_onehot.txt'`

**Comment by muhaochen** [comment]
See README:
https://github.com/muhaochen/seq_ppi/tree/master/binary/model
