### ISSUE TITLE
cannot find the file'../../../mtb/preprocessed/SKEMPI_seq.txt'

### ISSUE THREAD

**Issue by chang-bwl** [muhaochen/seq_ppi#14]
in regression problem,I cannot find the processed file'../../../mtb/preprocessed/SKEMPI_seq.txt';
following the readme,cannot download the normalized SKEMPI dataset;
please tell me where I can get it

**Comment by charlesxu90** [comment]
I met with similar issue. 
@chelseaju Any solutions to this problem? How can we try it?

**Comment by muhaochen** [comment]
I just tried to download myself through the link in the readme, and was able to do so. Will update with a Google Drive Link though.

**Comment by muhaochen** [comment]
Now you should be able to download it.

**Comment by charlesxu90** [comment]
Nice, thanks for the help.
