### ISSUE TITLE
Saving training results

### ISSUE THREAD

**Issue by gilless429** [muhaochen/seq_ppi#15]
Hello, I have been trying to set up and use your model but I have run into the issue that I do not see any currently existing code to save the results of the training once it is done, as the only output file I can see in rcnn.py is the one with the results on accuracy, precision, etc. with this code at the end :
with open(rst_file, 'w') as fp:
    fp.write('acc=' + str(accuracy) + '\tprec=' + str(prec) + '\trecall=' + str(recall) + '\tspec=' + str(spec) + '\tf1=' + str(f1) + '\tmcc=' + str(mcc))

I cannot see code for the creation of an H5 file with the saved model data.

Have I missed something which allows the results of training to be saved and used (if so, apologies) ?

**Comment by muhaochen** [comment]
That code was just to do cross validation. Indeed, if you want to save the model as H5, you need to add that line of code.

**Comment by muhaochen** [comment]
Say, after line 219 of https://github.com/muhaochen/seq_ppi/blob/master/binary/model/lasagna/rcnn.py, add a line to save the merge_model. That just saves a model in one fold of cross-validation though.

**Comment by gilless429** [comment]
Thank you very much for your answer, I will proceed that way.
