### ISSUE TITLE
Can you help me understand the calculation procedure of autocovariance (AC) vector?

### ISSUE THREAD

**Issue by lkhangkv1995** [muhaochen/seq_ppi#16]
It's a great paper. I will definitely cite your paper if I use the mentioned metrics.

I have a few confusions in the way we calculate protein-based AC vector (before concatenating with other protein P2)

From the formula (1) and (2) of your paper, given a max gap G (e.g, G=3) and given physicochemical features (i = 1,...,14):
-We have M=42 variables AC(i,g) [for each gap (g) and each feature (i)].
-If we sum up all the values of the j-th amino acid at this point like formula (1), we have no mean, std, min, and max values as there is only one value for each AC(i,g).

-Assume that we have not sum up yet: each AC(i,g) variable will have multiple values (each for each amino acid)
-We standardize (by mean and STD) these 42 variables and then min-max scale across all the values for each variable ,  if I understand correctly. 
-The resulting object is 42 arrays of within-variable scaled values.
-But I'm confused **how will we calculate the final 42-variable vector of the protein from these arrays.** By averaging or summing like the formula suggest?

Sorry for a technically detailed and awkward question.
Thank you very much. I would appreciate that if you clarify my confusion.

**Comment by muhaochen** [comment]
@chelseaju Can you help our colleague regarding the question on the AC values?

**Comment by lkhangkv1995** [comment]
I'm sorry for mistaking your paper with another paper (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2907-1). I will visit their website and ask the same question.
But I will also be grateful if you can clarify the issue. Thank you.

**Comment by chelseaju** [comment]
Thank you for your interests. We compute the AC vector based on the description of this paper - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2396404/. The concept is explained under MATERIALS AND METHODS - Feature extraction and AC.

**Comment by lkhangkv1995** [comment]
Thank you for your clarification. I'm able to follow and understand your works now. It seems like there are some diversifications of how we preprocess the AC vector and values.
