### ISSUE TITLE
FileNotFoundError while running cnn.py for binary PPI prediction

### ISSUE THREAD

**Issue by wasimaftab** [muhaochen/seq_ppi#4]
FileNotFoundError: [Errno 2] No such file or directory: '../../../sun/preprocessed/Supp-AB.tsv'

**Comment by muhaochen** [comment]
Please use run.sh to run the program. To run the cnn version, please change the rcnn.py in run.sh to cnn.py. Otherwise, the programs are set by default to read files from other datasets (Pan's dataset in this case).

**Comment by wasimaftab** [comment]
Thanks for your time. I would like to check inside the code using a debugger, therefore I would like to run it in an interactive fashion. However, I get another error
ImportError: cannot import name 'Merge' from 'keras.layers' 
Have you used keras 2.2.4?
according to the following link, Merge is not supported in Keras +2
https://stackoverflow.com/questions/56315726/cannot-import-name-merge-from-keras-layers

**Comment by muhaochen** [comment]
In that case removed Merge from import in cnn.py. It was not used.
