### ISSUE TITLE
Value Error: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by onionquan** [muhaochen/seq_ppi#5]
![image](https://user-images.githubusercontent.com/57767468/68879768-d24c7380-06be-11ea-9636-0169a7c01229.png)

**Comment by muhaochen** [comment]
Can you tell us which rcnn.py that was and which .sh you were using to run? Thanks.

**Comment by onionquan** [comment]
> Can you tell us which rcnn.py that was and which .sh you were using to run? Thanks.

I was using the ones in the regression folder, trying to predict the ddG value of mutations.

**Comment by auppunda** [comment]
I have this same problem. I used the one binary/model folder

**Comment by muhaochen** [comment]
Ankith, did you use the command in [run.sh](https://github.com/muhaochen/seq_ppi/blob/master/binary/model/run.sh) to run? There should not be a problem with the binary and multi-class tasks. Although I have heard people running into the problem with the dG task, I myself have tried to run the program in multiple environments, but have not encountered the problem yet.
FYI, you might need to change the code a little bit to save the model. I think Dat need a model file. See [here](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model) and add just one line.

**Comment by auppunda** [comment]
so i used the first python line "CUDA_VISIBLE_DEVICES=2 python rcnn.py ../../../yeast/preprocessed/protein.actions.tsv -1 results/yeast_wvctc_rcnn_50_5.txt 3 50 100" in run.sh to test it and I got that error.

**Comment by muhaochen** [comment]
I think I have found the bug ... Please pull.

**Comment by muhaochen** [comment]
A slight change to seq2tensor.py

**Comment by auppunda** [comment]
hi muhao, 
I'm still getting the same error. I tried recloning, but it still gives me this error. Thanks for the help

**Comment by muhaochen** [comment]
Ok.. I tracked all the way down to the embedding vector file vec5_CTC.txt and found two extra tabs... Now it should work. Thanks.
