### ISSUE TITLE
where is the default_onehot.txt?

### ISSUE THREAD

**Issue by bwang-ecnu** [muhaochen/seq_ppi#7]
Thanks for the source code you provided, I learned a lot from it. From rcnn.py, the 'default_onehot.txt' file should be in the 'embedding' folder, but I didn't find it. In addition, I would like to ask whether the word vectors of amino acids are obtained from the yeast database or from the database of all species?

**Comment by muhaochen** [comment]
Hi,

Sorry for the late reply. The token vectors were obtained on 8000 Homo sapiens protein sequences, as described in the paper. Also, please use the provided shell script to run the code. In that way you won't run into the option that needs "default_onehot.txt".

-MC

**Comment by bwang-ecnu** [comment]
Thank you for your answers! 
Wish everything goes well with your work!


wangbo
签名由网易邮箱大师定制
On 6/15/2020 02:07，Hamsterccolon<notifications@github.com> wrote：

Hi,

Sorry for the late reply. The token vectors were obtained on 8000 Homo sapiens protein sequences, as described in the paper. Also, please use the provided shell script to run the code. In that way you won't run into the option that needs "default_onehot.txt".

-MC
