### ISSUE TITLE
The accuracy of yeast dataset

### ISSUE THREAD

**Issue by bwang-ecnu** [muhaochen/seq_ppi#8]
I used the rcnn.py in the seq_ppi/binary/model/lasagna, but I get the average accuracy of yeast is around 95.6%. There are some differences from 97.02% in the article. Is there any need to modify the parameter settings in the program? Thank you very much！

**Comment by muhaochen** [comment]
Did you run using [run.sh](https://github.com/muhaochen/seq_ppi/blob/master/binary/model/run.sh)? What hidden state dimensionality did you use?
